# Harmony Jekyll theme general configurations 

# Base URL
baseurl: /

# Site live URL
url: http://www.zqlab.org

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Pixel XYZ
  # Little description about your site
  description: In order to be irreplaceable one must always be different.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   与像素有关，与互联网有关，奋斗在帝都的前端攻城师 Qian Zhu 的个人博客。
   记录技术、想法与成长，关注设计、用户体验和不经意的细节，爱 css、nodejs。
   爱学习，爱玩耍，爱编(měi)程(nǘ)。
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Qian Zhu
    email: nealzhuqian@gmail.com
    url: http://www.zqlab.org

  # Google Analytics key, leave blank to ignore
  google_analytics_key: 

  # Profile links, leave blank to ignore
  social: 
    github: nealzhu
    twitter: 
    facebook: 
    gplus: 
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink: /:year-:month-:day/:title.html

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
